[tool.ruff]
line-length = 101
lint.select = ["E", "F", "W", "I", "UP"]
lint.ignore = []

[tool.ruff.format]
quote-style = "double"

[tool.pytest.ini_options]
pythonpath = [
  "."
]

[project.optional-dependencies]
viz = [
    "pyproj==3.7.2",
    "simplekml==1.3.2",
    "simplekml==1.3.2",
]
